def Gallows(wrongDecision):
    if wrongDecision == 0:
        print("+-----+---")
        print("|     |   ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|_________")
    elif wrongDecision == 1:
        print("+-----+---")
        print("|     |   ")
        print("|     O   ")
        print("|         ")
        print("|         ")
        print("|_________")
    elif wrongDecision == 2:
        print("+-----+---")
        print("|     |   ")
        print("|     O   ")
        print("|     |   ")
        print("|         ")
        print("|_________")
    elif wrongDecision == 3:
        print("+-----+---")
        print("|     |   ")
        print("|     O   ")
        print("|    /|   ")
        print("|         ")
        print("|_________")
    elif wrongDecision == 4:
        print("+-----+---")
        print("|     |   ")
        print("|     O   ")
        print("|    /|\  ")
        print("|         ")
        print("|_________")
    elif wrongDecision == 5:
        print("+-----+---")
        print("|     |   ")
        print("|     O   ")
        print("|    /|\  ")
        print("|    /    ")
        print("|_________")
    elif wrongDecision == 6:        
        print("+-----+---")
        print("|     |   ")
        print("|     O   ")
        print("|    /|\  ")
        print("|    / \  ")
        print("|_________")