def Instruction():
    print("Gra Hangman powstała by zapewnić Ci odrobinę rozrywki")
    print("Hasło jest losowane z puli haseł i zakrywane, znasz tylko ilosć liter w haśle.")
    print("Początkowo wyświetla Ci się szubienica w następującej postaci:")
    print("+-----+---")
    print("|     |   ")
    print("|         ")
    print("|         ")
    print("|         ")
    print("|_________")
    print("By odgadnąć hasło można podawać litery, które mogą znajdować się w haśle.")
    print("Jeśli strzał będzie niecelny nasz ludek zacznie zawisać na szubienicy,")
    print("my tym samym będziemy się przybliżać do przegranej")
    print("Tak samo przy próbie zgadnięcie hasła i podania błędnego rozwiązania,")
    print("nasza postać zacznie zawisać na szubienicy")
    print("Ogólna liczba błędów, które można popełnić to 5")
    print("Litery już wybrane wyświetlają się na ekranie, nie są one również traktowane")
    print("jako błąd przy wprowadzeniu, wyświetla się tylko odpowiedni komunikat")
    print("Nasza gra kończy się gdy nasz ludzik zawiśnie na szubienicy:")
    print("+-----+---")
    print("|     |   ")
    print("|     O   ")
    print("|    /|\  ")
    print("|    / \  ")
    print("|_________")
    print("Grę wygrywamy gdy trafimy wszystkie litery z hasła lub gdy odgadniemy hasło")
    print("Życzę miłęj zabawy. ;)")